# Generated by Django 2.2.1 on 2019-07-22 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.DateField()),
                ('catagory', models.IntegerField(choices=[(1, 'Class Response'), (2, 'Fight'), (3, 'Misbehave')], default='1', max_length=1)),
                ('scale', models.IntegerField(choices=[(-1, 'very Bad'), (-2, 'Bad'), (0, 'Normal'), (1, 'Good'), (2, 'Very Good')], default='0', max_length=1)),
                ('content', models.TextField()),
                ('check', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
