# Generated by Django 2.2.1 on 2019-07-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('behaviour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
            preserve_default=False,
        ),
    ]
