# Generated by Django 2.2.1 on 2019-06-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdairy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classdairy',
        ),
    ]
