# Generated by Django 2.2.1 on 2019-06-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdairy', '0003_classdairy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdairy',
            old_name='gender',
            new_name='subject',
        ),
    ]
