# Generated by Django 2.2.1 on 2019-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdairy', '0004_auto_20190629_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdairy',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
