# Generated by Django 2.2.1 on 2019-06-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classdairy', '0005_auto_20190629_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classdairy',
        ),
    ]
