# Generated by Django 2.2.1 on 2019-07-28 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classdairy', '0008_auto_20190727_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdairy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
