# Generated by Django 2.2.3 on 2019-09-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdairy', '0009_auto_20190728_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdairy',
            name='subject',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], default='E', max_length=1),
        ),
    ]
