# Generated by Django 2.2.1 on 2019-07-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clss.Clss')),
            ],
        ),
    ]
