# Generated by Django 2.2.1 on 2019-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='class1',
            new_name='sub',
        ),
        migrations.AddField(
            model_name='subject',
            name='full_mark',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
